name: Check deps for freshness

on:
  schedule:
    - cron: '0 1 1 * *' # every first of the month
  pull_request:
    types: [opened, reopened]

jobs:
  deps:
    runs-on: ubuntu-22.04

    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Cache lein project dependencies
      uses: actions/cache@v4
      with:
        path: "~/.m2/repository"
        key: "${{ runner.os }}-clojure-${{ hashFiles('**/project.clj') }}"

    - name: Install clj runtime
      run: |
        .github/workflows/install-binaries.sh
        echo "${PWD}/bin" >> $GITHUB_PATH

    - name: Check dependency freshness
      run: make antq
