name: Check deps

on:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  deps:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: NVD clojure
      uses: jomco/nvd-clojure-action@v1
