name: Build and publish docker image

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v[0-9]+.[0-9]+'

jobs:
  docker:
    runs-on: ubuntu-22.04
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.6.0
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5.7.0
        with:
          images: eduhub-docker-production.artie.ia.surfsara.nl/rio-mapper
          tags: |
            type=match,pattern=v\d+.\d+
            type=sha,format=long
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.11.1
      - name: Login to Docker Hub
        uses: docker/login-action@v3.4.0
        with:
          registry: eduhub-docker-production.artie.ia.surfsara.nl
          username: ${{ secrets.ARTIFACTORY_USERNAME }}
          password: ${{ secrets.ARTIFACTORY_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v6.18
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
