name: Check deps for vulnerabilities

on:
  push:
    branches: ["*"]
    tags: ["*"]
  schedule:
    - cron: '0 1 * * 1,2,3,4,5' # every workday

jobs:
  deps:
    runs-on: ubuntu-22.04

    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Cache lein project dependencies
      uses: actions/cache@v4
      with:
        path: "~/.m2/repository"
        key: "${{ runner.os }}-clojure-${{ hashFiles('**/project.clj') }}"

    - name: Install clj runtime
      run: |
        .github/workflows/install-binaries.sh
        echo "${PWD}/bin" >> $GITHUB_PATH

    - name: Check that NVD Secret is set
      env:
        NVD_API_TOKEN: ${{ secrets.NVD_API_TOKEN }}
      if: ${{ env.NVD_API_TOKEN == '' }}
      run: echo "NVD_API_TOKEN secret is empty"; exit 1

    - name: Check clojure dependencies with NVD
      env:
        CLJ_WATSON_NVD_API_KEY: ${{ secrets.NVD_API_TOKEN }}
      run: |
        make watson
