name: Check deps for vulnerabilities

on:
  push:
    branches: ["*"]
    tags: ["*"]
  schedule:
    - cron: '0 1 * * 1,2,3,4,5' # every workday

jobs:
  deps:
    runs-on: ubuntu-latest

    env:
      NVD_API_TOKEN: ${{ secrets.NVD_API_TOKEN }}

    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Cache lein project dependencies
      uses: actions/cache@v4
      with:
        path: "~/.m2/repository"
        key: "${{ runner.os }}-clojure-${{ hashFiles('**/project.clj') }}"

    - name: NVD clojure
      uses: jomco/nvd-clojure-action@v3
