name: Run tests
on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: lein deps

    - name: Check dependency freshness
      run: lein ancient check :no-profiles

    - name: Run linters
      run: lein lint
      
    - name: Run checks
      run: lein check

    - name: Run tests
      run: lein test

    - name: Start Redis
      uses: supercharge/redis-github-action@1.4.0
      with:
        redis-version: 6.2

    - name: Run tests with redis
      run: lein test :redis

    - name: Proof data specs
      run: lein proof-specs

    - name: Check function specs
      run: lein check-specs
      continue-on-error: true
      
    - name: Run compile
      run: lein uberjar
