name: Run tests
on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: lein deps

    - name: Run linters
      run: lein lint

    - name: Run tests
      run: lein test

    - name: Run checks
      run: lein check

    - name: Run compile
      run: lein uberjar

  deps:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: lein deps

    - name: Check dependency freshness
      run: lein ancient check :no-profiles

  specs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: lein deps

    - name: Proof specs
      run: lein proof-specs

    - name: Check function specs
      run: lein check-specs

