name: Check if RIO queue is up or down

on:
  push:
    branches:
      - 'main'
      - 'test-rio'
#    - cron: '6 9-17 * * 1-5' # every hour on weekdays during working hours

jobs:
  deps:
    runs-on: ubuntu-latest

    steps:
      - name: Cache lein project dependencies
        uses: actions/cache@v4
        with:
          path: "~/.m2/repository"
          key: "${{ runner.os }}-clojure-${{ hashFiles('**/project.clj') }}"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup certificate stores
        env:
          KEYSTORE_JKS_B64: ${{ secrets.KEYSTORE_JKS_B64 }}
          TRUSTSTORE_JKS_B64: ${{ secrets.TRUSTSTORE_JKS_B64 }}
        run: |
          echo "$KEYSTORE_JKS_B64" | base64 -d > keystore.jks
          echo "$TRUSTSTORE_JKS_B64" | base64 -d > truststore.jks          

      - name: Check rio queue status
        env:
          CLIENTS_INFO_PATH: ${{ secrets.CLIENTS_INFO_PATH }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          GATEWAY_PASSWORD: ${{ secrets.GATEWAY_PASSWORD }}
          GATEWAY_ROOT_URL: ${{ secrets.GATEWAY_ROOT_URL }}
          GATEWAY_USER: ${{ secrets.GATEWAY_USER }}
          KEYSTORE: keystore.jks
          KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          OS_AUTH_URL: ${{ secrets.OS_AUTH_URL }}
          OS_CONTAINER_NAME: ${{ secrets.OS_CONTAINER_NAME }}
          OS_PASSWORD: ${{ secrets.OS_PASSWORD }}
          OS_PROJECT_NAME: ${{ secrets.OS_PROJECT_NAME }}
          OS_USERNAME: ${{ secrets.OS_USERNAME }}
          RIO_READ_URL: ${{ secrets.RIO_READ_URL }}
          RIO_RECIPIENT_OIN: ${{ secrets.RIO_RECIPIENT_OIN }}
          RIO_SENDER_OIN: ${{ secrets.RIO_SENDER_OIN }}
          RIO_RETRY_ATTEMPTS_SECONDS: '5,10,15'
          RIO_UPDATE_URL: ${{ secrets.RIO_UPDATE_URL }}
          STORE_HTTP_REQUESTS: true
          SURF_CONEXT_CLIENT_ID: ${{ secrets.SURF_CONEXT_CLIENT_ID }}
          SURF_CONEXT_CLIENT_SECRET: ${{ secrets.SURF_CONEXT_CLIENT_SECRET }}
          SURF_CONEXT_INTROSPECTION_ENDPOINT: ${{ secrets.SURF_CONEXT_INTROSPECTION_ENDPOINT }}
          TOKEN_ENDPOINT: ${{ secrets.TOKEN_ENDPOINT }}
          TRUSTSTORE: truststore.jks
          TRUSTSTORE_PASSWORD: ${{ secrets.TRUSTSTORE_PASSWORD }}
        run: lein mapper test-rio rio-mapper-dev.jomco.nl
